### PR TITLE
progmem fix saves 440 bytes of dynamic memory.

### PR DESCRIPTION
**Pull request by Jaycar-Electronics**
Changing the structure of the array removes it from global dynamic memory and places in PROGMEM. 

it is better to store this data in ROM so that it saves space for program.
| Change | Program Space | data / variable space | 
| ---- | ---------- | --------- |
| Before | 4628 (14%) from 32kb | 1110 bytes (**54%**) | 
| After | 5066 (15%) from 32kb | 690 bytes (**33%**) | 

this means programs can include more things, such as when using screens, as more of the dynamic memory is saved to handle bigger objects and data.

### CODE REVIEW

**Comment by Pillar1989** [comment]
`PROGMEM` ? @Jaycar-Electronics  What platform are you testing?

**Comment by Jaycar-Electronics** [comment]
ah good point, this is for atmega / arduino based code.

**Comment by Pillar1989** [comment]
So it is better to add a macro definition to determine whether it is an AVR platform or not, because arduino also has platforms such as ARM and ESP. @Jaycar-Electronics

**Comment by Jaycar-Electronics** [comment]
yep, added now; 
ESP32 and ESP8266 both have macros for PROGMEM and will compile successfully. anything else will just use dynamic version.

**Comment by Pillar1989** [comment]
Thanks

**Pull request merged**
